# This service hogs CPU from time to time. No use of it anyways
- name: "Stop avahi-daemon"
  become: true
  loop:
    - "avahi-daemon.service"
    - "avahi-daemon.socket"
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: false
    masked: true
    state: "stopped"
  tags: ["system"]

- name: "Disable Bluetooth auto enable"
  become: true
  notify: "Restart bluetooth"
  community.general.ini_file:
    path: "/etc/bluetooth/main.conf"
    section: "Policy"
    option: "AutoEnable"
    value: "false"
    no_extra_spaces: true
    backup: true
    mode: "644"
  tags: ["system"]

- name: "Install Apt programs"
  become: true
  loop:
    - "gnome-tweaks"
    - "gufw"
    - "htop"
    - "jq"
    - "ncdu"
    - "neovim"
    - "terminator"
    - "ubuntu-restricted-extras"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  tags: ["apt"]

- name: Install Snap packages
  become: true
  loop:
    - "spotify"
    - "pinta"
  community.general.snap:
    name: "{{ item }}"
    state: "present"
  tags: ["snap"]

- name: "Enable UFW firewall"
  become: true
  community.general.ufw:
    logging: "off"
    state: "enabled"
  tags: ["ufw"]

- name: "Link Terminator"
  become: true
  community.general.alternatives:
    name: "x-terminal-emulator"
    link: "/usr/bin/x-terminal-emulator"
    path: "/usr/bin/terminator"
    priority: 50
  tags: ["terminator"]

- name: "Make Terminator default terminal"
  community.general.dconf:
    key: "/org/gnome/desktop/applications/terminal/exec"
    value: "'terminator'"
    state: "present"
  tags: ["terminator"]

- name: "Set terminal execution argument"
  community.general.dconf:
    key: "/org/gnome/desktop/applications/terminal/exec-arg"
    value: "'-x'"
    state: "present"
  tags: ["terminator"]

- name: "Enable git bash completion"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      # Set git autocompletion
      source /usr/share/bash-completion/completions/git
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: GIT"
    path: "{{ ansible_facts.env.HOME }}/.bashrc"
    prepend_newline: true
  tags: ["autocomplete"]

- name: "Download DBeaver .deb package"
  ansible.builtin.get_url:
    url: "https://dbeaver.io/files/dbeaver-ce-latest-linux-x86_64.deb"
    dest: "/tmp/dbeaver-ce-latest-linux-x86_64.deb"
    mode: "0644"
  tags: [dbeaver]

- name: "Install DBeaver"
  become: true
  ansible.builtin.apt:
    deb: "/tmp/dbeaver-ce-latest-linux-x86_64.deb"
    state: "present"
  tags: [dbeaver]

- name: "Install Terraform dependencies"
  become: true
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
    state: present
    update_cache: true
  tags: ["terraform"]

- name: "Download HashiCorp GPG key"
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: "0644"
  tags: ["terraform"]

- name: "Dearmor and install GPG key"
  become: true
  ansible.builtin.shell:
    cmd: gpg --dearmor < /tmp/hashicorp.gpg > /usr/share/keyrings/hashicorp-archive-keyring.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  tags: ["terraform"]

- name: Add HashiCorp apt repository
  become: true
  ansible.builtin.shell:
    cmd: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    creates: /etc/apt/sources.list.d/hashicorp.list
  tags: ["terraform"]

- name: Install Terraform
  become: true
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
  tags: ["terraform"]

- name: Download and dearmor Google Cloud GPG key
  become: true
  ansible.builtin.shell:
    cmd: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    creates: /usr/share/keyrings/cloud.google.gpg
  tags: ["gcloud"]

- name: Add Google Cloud SDK apt repository
  become: true
  ansible.builtin.shell:
    cmd: |
      echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    creates: /etc/apt/sources.list.d/google-cloud-sdk.list
  tags: ["gcloud"]

- name: Install Google Cloud CLI
  become: true
  ansible.builtin.apt:
    name: google-cloud-cli
    state: present
    update_cache: true
  tags: ["gcloud"]

- name: "Install nvm"
  ansible.builtin.shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.5/install.sh | bash
    creates: "{{ ansible_facts.env.HOME }}/.nvm/nvm.sh"
  tags: ["nvm"]

- name: "Install Node and set as default"
  ansible.builtin.shell:
    cmd: |
      source "{{ ansible_facts.env.HOME }}/.nvm/nvm.sh"
      nvm install {{ setup_laptop_node_version }}
      nvm alias default {{ setup_laptop_node_version }}
    executable: /bin/bash
  tags: ["nvm"]
