apiVersion: v2
version: 1.0.0
name: grafana
description: Better graphs and visualization for Firefly III
type: application
dependencies:
  - name: grafana
    version: "12.0.1"
    repository: oci://ghcr.io/grafana-community/helm-charts
