grafanaUser:
  grafana_namespace: monitoring
  grafana_namespace_user: AgBNPbR33TVyuxbpW8olwFXMzli0sWi/IBFPcKSmdWhgisb2fN5nQNueULGGV+tl8NnrBQEXkAqjSFJ+5g9M9zkvyOhk+ZeZ6ctQ/3Gd9Ef9teMiRj/gv4PIgD3fHCg19Mv69w+CHMRDqqNAC3nzrLsJGyRCjUV+hMxqYtezDIQvK2b8Y5werhMcXydE59b41IB0WzOG8F8vKj1zbu7GZkCE4E63BDk0NbHrtzuqbAzrN59hYNMRrZtzOBV+3EjJ99QE7uoETaw/h1peIkMls/1Pz/3fYQYXCnQf/oAmduqRXLvnhi9xMggSeX/B1qqgTTHAP4HjSUIONA7l8Y4UqOJEDhOBEv9vMGveDBoY3xByZSCJlUQ+oU/f6/z3y5LmlSQPRFLHAvo1W/abxccFq+qN9c2a/LLFCKpaH2eFPRqa6msQ3RAgxN7kSP0Y+UebjwvnTbyye+v0OBuNEOKec+dpdMf0bCY7ceeAPM9Pcz/33r/tnQn4SiLSdhVrfG7JWdp/rS4Q5dO5Ul5f3TFk7c90mBcTVQcAxBq+fxacAy/Cm1rK/Q8mmi+alF88PyZBG75rGumQhlTFni2y7C6e/pRESZoQ5SzK6KtT4RaU5clPgNN90hp21IGruwwlvnH79Kv99DQdZfcJeWeZ4FbOn1rEYMTYYLXc0VVeC2Oo9KnH8L/3eTJHqWsISHN/qDb98ODEax4GD2M9
  grafana_namespace_password: AgDYj72UR+kyfMBoRs7dvWGPfql9jo2XC/rMrxnUauCGKVmvc15kEM7I93neH+I/UUqK1UO5omR5z/GSF/lhelo5bBUQm58UdAqPX8pB/SiPHeWgDHi6d2ZraqxqrrJE+pojyfVYxPb4LPsac8RC15nE6kAhNrCmpym1iDz8JKEOn6/jxg+hQnPU8hzO9znmDwKEJvtiwlnDwZR7rugaiPLZBOmZJ+GXbfS2W+/y+4YgD48a5/2+unrjIcwXDyQQiZJbqoHaMUh3dHzFNsMw57fMr8M6gn7+UCf9MAECTE+7iS7MAHTXwv/FCFJL1DTqx5+ZixiqgbUYd+vExaOWvJkaTeigRsNs//IerLsKIHztHTObxk4ZGUKucH+WRydV1ZXHKHcFQaL0YvHuZW7RjSDhLoGcHMKa9fT6TyIUcH01lC7qR5PdTL04SbNvvvjnEzE47Mk4MGYWTwoqKMHijcNz3ubVhtcvL8o6IhhtSLY+QGw+HIiv4PUfU22YHBMPWYB4Vs/Potd3gq5jddZ6L+ztdtvrQaMqHBtisBHAi5VbhcvIOhVr9sQUqfj7ZELaCVNARJxhV3KeYB6kBdG22tmuDAmrx4s8pbZ7dPL9BuTXyMreWdS50QqxMGfKfidQpBP1KI53IK8K+Gwg1uHZMvHIlihu/Rx972O5nol9e0dA7hcQS/0Z+5YE0xvQpOz44susmJfPto//5uVwkZwnNQ5py0cPwvZjyy0k8t4SnrCQLg==
  firefly_namespace_user: AgBLS/mQ32R/xVt9ORphtJoa0EQM+p7hdhhBIkJgMoCnO8vme9Uaj9NInWzpBP91ngfA0GH8MEZ9tUdqQWfAhEAV2ExtHc8uGiKfpZ12ViIy9GsFoeZrNj++yG8xSoMN0lJ4PDaImE+sdg9Ed+hbOZmkUL4hRqHuwPFsmHj/dJsXHeAh1HjTx934wF0U9FA4u5v7oX0NmTKPui/1BJDFEsjRXzE041KxfXnxDmD/vKulmw4PEF4Rmyd8EpX8XYkXm3Ivth8J9wVrZfN6UAccYuJlI2yslpyqu4FCc1cCGsZ8oayyxTRVWF9s1conHsLVRVVeVXNxj7ewU7wx22/7C3GxR0JdWJqAjD5wATyGZ3ohOdCEX9rm11lELITB+ZnjKN8QGYxpeWNyTTcrueux8oNCmdVOGIFqFnF6ldo4mDOP24IR4k+jqY0SI/cdpv4moUL5hn5r1HV9aJ+bJogkJ73eixVZE8emfEArAiRsCaC1C/LnBPjMT+8sUEgjKjZyyC7iLFXhj+hBS0csjSG5Kw1q4gEmbYqV7ie4CPxVPvLn6F1GCaL1FWY8DLNnQdoKFRfBqwujlCe1lGrWvFduBoDeshQ5B58PzFW8b5jQrbuTyqp8kO0UJbFJ8FME08Nr2WmEYkm0DiTwSkkzipuU8TP8L1AoE0E49tB33a4hrkkB+MzFcIaSeGrzzuwrj+GLDqXumGl5jW9C
  firefly_namespace_password: AgCCQ+0tj01UldadTlrzbbIev40587zz71rgcgujff9r/sQVA4JRZAuSGjFKEzegzcdHKRXJeqLucHZlitFI+IGENb3a3sSWjHGRGCYengzkZISOj9Bi0wSl03vzbZ4tGft/IA7oGKjpIE1Cm1pkU4FZDDMZLi5PDEdozs2DQWNURSjBcrAeLJeFWoe0Ci8bzxCzVCZaG1wRtigrkbEtZ/e7aPqTC+AhSLbv9GEhGJrCOo4EeR6fRFP8VFPk9dIU5wl08PoS76l28XEcYGiRTCwESyzhphL+q8XSZ6/qlfwj8IIunITazU++JTgsqL/6E8trpSeirY2HLzgUhZiv/h4cVwXuPmmvD/muc3ZqM8UGhIgkFxMKonbfLR6UQKnSVRIz3JFXYX9x4tCY+vXl+C5RZB3JD6H1EbaOm5AtpPvEcnUKxv2ETGkyQF+xqyreNenfgsWIbzkBSHl8WRxxmpm0JH6BTKh+OSa0zqawJ359+WmVAlHbvnZPIe6J4vnBrD0x1pUzLfHaH347vN5x69zJW8vFV3ycjlul3lKGZ+SgTnnJR9rsEq4FNMGMmPBD+ORczBqch1QGbCJWskz6ejP7I3v1i9AjFD1BSWoE2tL7DU/pwLi2OfEi6hyF3vcjXTJguPmOx1886BReBwIvvmGJfIQkZ9Szi/WUdfsfsey5s5c80d4ijr1+hGwqzZOaMXE0J2VrnqXmzL0amcChMiiF6OIFQU6JyEUeuTkUdqJLpA==

httpRoute:
  enabled: true
  hostnames:
    - firefly.homelab.me
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-api
      namespace: infrastructure
      sectionName: https
  rules:
    - backendRefs:
        - kind: Service
          name: firefly-firefly-iii
          group: ""
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

psqlClient:
  image: alpine/psql
  tag: 17.5

firefly-iii-stack:
  firefly-db:
    backupSchedule: null
    image:
      tag: 17-alpine
    storage:
      accessModes: ReadWriteOnce
    configs:
      BACKUP_ENABLED: false
      RESTORE_ENABLED: false
      TZ: Europe/Paris
  firefly-iii:
    config:
      env:
        TRUSTED_PROXIES: "*"
        TZ: Europe/Paris
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  importer:
    enabled: false
