httpRoute:
  enabled: true
  hostnames:
    - firefly.homelab.me
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-api
      namespace: infrastructure
      sectionName: https
  rules:
    - backendRefs:
        - kind: Service
          name: firefly-firefly-iii
          group: ""
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

customDbImage:
  image: alpine/psql
  tag: 17.5

firefly-iii-stack:
  firefly-db:
    backupSchedule: null
    image:
      tag: 17-alpine
    storage:
      accessModes: ReadWriteOnce
    configs:
      BACKUP_ENABLED: false
      RESTORE_ENABLED: false
      TZ: Europe/Paris
  firefly-iii:
    config:
      env:
        TRUSTED_PROXIES: "*"
        TZ: Europe/Paris
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  importer:
    enabled: false
