domain: firefly.homelab.me

customDbImage:
  image: alpine/psql
  tag: 17.5

firefly-iii-stack:
  firefly-db:
    image:
      tag: 17-alpine
    storage:
      accessModes: ReadWriteOnce
    configs:
      BACKUP_ENABLED: false
      RESTORE_ENABLED: false
  firefly-iii:
    config:
      env:
        TRUSTED_PROXIES: "*"
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
  importer:
    enabled: false
