- name: "Create Firefly backup folder"
  ansible.builtin.file:
    path: "{{ firefly_backup_directory }}"
    state: directory
    mode: "0755"

- name: "Get Firefly backup PVC volume"
  changed_when: false
  register: firefly_backup_pvc_volume
  ansible.builtin.shell:
    cmd: "kubectl get pvc -n finance firefly-firefly-db-backup-storage-claim -o jsonpath='{.spec.volumeName}'"

- name: "Find the host directory of the PVC"
  become: true
  failed_when: pvc_folder_search.matched != 1
  register: pvc_folder_search
  ansible.builtin.find:
    file_type: "directory"
    paths: "/var/lib/rancher/k3s/storage"
    patterns: "{{ firefly_backup_pvc_volume.stdout }}*"
    recurse: no

- name: Launch DB backup job
  ansible.builtin.shell:
    cmd: |
      kubectl create job --from=cronjob/firefly-firefly-db-backup firefly-firefly-db-backup-job -n finance
      kubectl wait --for=condition=complete job firefly-firefly-db-backup-job --timeout=30s -n finance

- name: "Backup Firefly DB dump to host"
  become: true
  ansible.builtin.copy:
    dest: "{{ firefly_backup_directory }}/firefly_{{ ansible_date_time.iso8601_basic_short }}.sql"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    remote_src: true
    src: "{{ pvc_folder_search.files[0].path }}/firefly.sql"
