apiVersion: v2
version: 1.0.0
name: argocd
description: Deploy ArgoCD on homelab.
type: application
dependencies:
  - name: "argo-cd"
    version: "9.5.17"
    repository: "https://argoproj.github.io/argo-helm"
    alias: argocd
