apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "firefly.certificate" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "firefly.certificate" . }}
  isCA: false
  usages:
    - server auth
  dnsNames:
    - "{{ .Values.domain }}"
  issuerRef:
    name: cert-manager-certmanager
    kind: ClusterIssuer
