apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "firefly-iii.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firefly-iii.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.domain }}`)
      priority: 10
      services:
        - name: {{ .Release.Name }}-firefly-iii
          port: {{ index .Values "firefly-iii-stack" "firefly-iii" "service" "port" }}
  tls:
    secretName: {{ include "firefly.certificate" . }}
