- name: "Install k9s"
  ansible.builtin.import_tasks: "k9s.yml"
  tags: "k9s"

- name: "Install kubectl"
  ansible.builtin.import_tasks: "kubectl.yml"
  tags: "kubectl"

- name: "Install Helm"
  ansible.builtin.import_tasks: "helm.yml"
  tags: "helm"
