alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 50Mi
        cpu: 50m

grafana:
  resources:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 100m

kube-state-metrics:
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

prometheus-node-exporter:
  resources:
    limits:
      cpu: 150m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi

prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 50Mi

prometheus:
  prometheusSpec:
    resources:
      limits:
        memory: 500Mi
        cpu: 500m
      requests:
        memory: 250Mi
        cpu: 100m
