metallb:
  controller:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

  speaker:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

addresses:
- 192.168.168.0/24