apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-lab
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: file:///home/lamvng/argocd-sync/home-lab
        revision: develop
        directories:
          - path: kube/applications/*/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: file:///home/lamvng/argocd-sync/home-lab
        targetRevision: develop
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
