{{- /*
Traefik ingress for K3S
*/}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "argo-cd.server.fullname" .Subcharts.argocd }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo-cd.labels" (dict "context" .Subcharts.argocd "component" .Values.argocd.server.name "name" .Values.argocd.server.name) | nindent 4 }}
    {{- with .Values.argocd.server.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.argocd.server.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.argocd.global.domain }}`)
      priority: 10
      services:
        - name: {{ template "argo-cd.server.fullname" .Subcharts.argocd }}
          port: {{ .Values.argocd.server.service.servicePortHttp }}
    - kind: Rule
      match: Host(`{{ .Values.argocd.global.domain }}`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: {{ template "argo-cd.server.fullname" .Subcharts.argocd }}
          port: {{ .Values.argocd.server.service.servicePortHttp }}
          scheme: h2c
  tls:
    secretName: {{ include "argocd.server.certificate" . }}
