apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: firefly-db
    chart: firefly-db-0.2.9
    heritage: Helm
    release: firefly
  name: firefly-firefly-db-restore
  namespace: finance
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          psql -h $DBHOST -p $DBPORT -U $DBUSER < /var/lib/backup/${DBNAME}.sql
          echo "done"
        envFrom:
        - configMapRef:
            name: firefly-firefly-db-config
        image: alpine/psql:17.5
        imagePullPolicy: IfNotPresent
        name: firefly-firefly-db-restore
        volumeMounts:
        - mountPath: /var/lib/backup
          name: backup-storage
      restartPolicy: Never
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: firefly-firefly-db-backup-storage-claim
  ttlSecondsAfterFinished: 100
