helm_version: "v3.18.4"
kubecolor_version: "v0.5.1"
kubectl_version: "v1.33.3"
k9s_version: "v0.50.7"

kubectl_binary_tmp_path: "/tmp/kubectl"
kubectl_binary_path: "/usr/local/bin/kubectl"
kubectl_sha256_path: "/tmp/kubectl.sha256"

k9s_deb_path: "/tmp/k9s_linux_amd64.deb"
