apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    repoURL: https://github.com/lamvng/home-lab.git
    path: charts/infra
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
