- name: "Backup & Restore Firefly DB"
  hosts: "localhost"

  vars_prompt:
    - name: "firefly_db_dump_encrypt_password"
      prompt: "Password to encrypt Firefly DB dump"
      private: true

  roles:
    - role: "firefly_db"
