apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: charts/argocd
    repoURL: https://github.com/lamvng/home-lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


  source:
    repoURL: https://github.com/lamvng/home-lab.git
    path: application_cluster_management/
    targetRevision: HEAD
