- name: Download K9S binary
  ansible.builtin.get_url:
    dest: "{{ k9s_deb_path }}"
    mode: "0644"
    url: "{{ k9s_deb_url }}"

- name: Install k9s .deb package
  become: true
  ansible.builtin.apt:
    deb: "{{ k9s_deb_path }}"
    state: present
