apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: firefly-firefly-iii-certificate
  namespace: finance
spec:
  secretName: firefly-firefly-iii-certificate
  isCA: false
  usages:
    - server auth
  dnsNames:
    - "firefly.homelab.me"
  issuerRef:
    name: cert-manager-certmanager
    kind: ClusterIssuer

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: firefly-importer-certificate
  namespace: finance
spec:
  secretName: firefly-importer-certificate
  isCA: false
  usages:
    - server auth
  dnsNames:
    - "firefly-importer.homelab.me"
  issuerRef:
    name: cert-manager-certmanager
    kind: ClusterIssuer
