# 1. Use Helm chart over Kustomize deployment, for personal preference of PostgreSQL over MySQL.
# - The Kustomize manifests use MySQL, and has `mysql` string everywhere. Not practical to patch them all manually.
#   See https://github.com/firefly-iii/kubernetes/tree/5278a7b5a5b013c0d3ac564ed38b7ef80c725fbf/kustomize.
# - The Helm chart uses Postgres by default, and there is no reference of specific technology used.
#   See https://github.com/firefly-iii/kubernetes/tree/5278a7b5a5b013c0d3ac564ed38b7ef80c725fbf/charts/firefly-db.

# 2. This should be more straightforward by deploying just the vanilla Helm chart.
# Context: However, the chart contains a pre-upgrade Helm hook, which creates a DB backup before any `helm upgrade`.
# ArgoCD treats pre-upgrade and pre-install Helm hooks the same way, as an ArgoCD PreSync hook.
# The PreSync hook is executed before each sync, and requires the database (PVC) to be present. 
# Problem: On the first installation, the sync falls into a deadlock, where:
# - The PreSync hook is executed first, tries to do a job on a non-existent PVC, and fails.
# - The PVC cannot be provisioned as long as the PreSync job has not finished.
# See https://github.com/argoproj/argo-cd/issues/7536.
# Workaround: Remove the hook.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
helmCharts:
  - name: firefly-iii-stack
    repo: https://firefly-iii.github.io/kubernetes
    version: 0.9.1
    releaseName: firefly
    namespace: finance
    valuesFile: values.yaml
    valuesMerge: merge
    skipHooks: true

resources:
  - traefikIngress.yaml
  - certificate.yaml

patches:
  - path: db-cronjob-patch.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: firefly-firefly-db-backup
