# This should be more straightforward by deploying just the vanilla Helm chart.
# Context: However, the chart contains a pre-upgrade Helm hook, which creates a DB backup before any `helm upgrade`.
# ArgoCD treats pre-upgrade and pre-install Helm hooks the same way, as an ArgoCD PreSync hook.
# The PreSync hook requires the database (PVC) to be present, and is executed before each sync.
# Problem: On the first installation, the sync falls into a deadlock, where:
# - The PreSync hook is executed first, tries to do a job on a non-existent PVC, and fails.
# - The PVC cannot be provisioned as long as the PreSync job has not finished.
# See https://github.com/argoproj/argo-cd/issues/7536.
# Workaround: Skip this hook by using a Kustomize wrapper over the Helm chart.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefikIngress.yaml

helmCharts:
  - name: firefly-iii-stack
    repo: https://firefly-iii.github.io/kubernetes
    version: 0.9.0
    releaseName: firefly
    namespace: finance
    valuesFile: values.yaml
    valuesMerge: merge
    skipHooks: true
