firefly-db:
  image:
    tag: 17-alpine
  storage:
    accessModes: ReadWriteOnce
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
firefly-iii:
  image:
    tag: version-6.5.9
  config:
    env:
      TRUSTED_PROXIES: "*"
  resources:
    requests:
      memory: 128Mi
      cpu: 150m
    limits:
      memory: 512Mi
      cpu: 500m
importer:
  enabled: false
  fireflyiii:
    url: "http://firefly-firefly-iii.finance.svc.cluster.local:80"
    vanityUrl: "https://firefly.homelab.me"
  config:
    env:
      TRUSTED_PROXIES: "*"
  resources:
    requests:
      memory: 128Mi
      cpu: 150m
    limits:
      memory: 512Mi
      cpu: 500m
