- name: "Install ArgoCD via Helm for the first time"
  kubernetes.core.helm:
    chart_ref: "argo-cd"
    chart_repo_url: "https://argoproj.github.io/argo-helm"
    create_namespace: true
    release_name: "{{ argocd_name }}"
    release_namespace: "{{ argocd_name }}"
    values: "{{ lookup('file', role_path + '/files/values.yaml') | from_yaml | dict2items | selectattr('key', 'equalto', 'argocd') | map(attribute='value') | first }}"

- name: "Add ArgoCD in hosts"
  become: true
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      127.0.0.1 {{ argocd_host }}
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: ARGOCD"
    path: "/etc/hosts"
    prepend_newline: true

# TODO: BUG here
# - name: Wait for ArgoCD server to be ready
#   loop:
#     - "{{ argocd_name }}-server"
#     - "{{ argocd_name }}-repo-server"
#   kubernetes.core.k8s_info:
#     api_version: "apps/v1"
#     kind: "Deployment"
#     name: "{{ item }}"
#     namespace: "{{ argocd_name }}"
#   register: "argocd_deploy"
#   retries: 50
#   delay: 5
#   until:
#     - argocd_deploy.resources | length > 0
#     - argocd_deploy.resources[0].status.availableReplicas is defined
#     - argocd_deploy.resources[0].status.availableReplicas > 0

- name: "Deploy root app"
  kubernetes.core.k8s:
    namespace: "{{ argocd_name }}"
    state: present
    src: "{{ role_path }}/files/root-app.yaml"
