- name: "Install ArgoCD via Helm for the first time"
  kubernetes.core.helm:
    chart_ref: "argo-cd"
    chart_repo_url: "https://argoproj.github.io/argo-helm"
    create_namespace: true
    release_name: "{{ argocd_name }}"
    release_namespace: "{{ argocd_name }}"
    values: "{{ lookup('file', role_path + '/files/values.yaml') | from_yaml | dict2items | selectattr('key', 'equalto', 'argocd') | map(attribute='value') | first }}"

- name: "Enable argocd bash completion"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      # Set argocd autocompletion
      source <(argocd completion bash)
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: ARGOCD"
    path: "{{ ansible_env.HOME }}/.bashrc"
    prepend_newline: true

- name: "Add ArgoCD in hosts"
  become: true
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      127.0.0.1 {{ argocd_host }}
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK: ARGOCD"
    path: "/etc/hosts"
    prepend_newline: true

- name: "Wait for ArgoCD to be ready"
  delay: 5
  retries: 12
  ansible.builtin.uri:
    method: "GET"
    status_code: 200
    timeout: 1
    url: "https://{{ argocd_host }}/healthz"
    validate_certs: false

- name: "Deploy root app"
  ansible.builtin.shell:
    cmd: "kubectl apply -n {{ argocd_name }} -f {{ role_path }}/files/root-app.yaml"

