- name: "Launch DB backup job"
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/db_backup_job.yaml"

- name: "Wait for DB backup job to complete"
  kubernetes.core.k8s_info:
    kind: Job
    name: firefly-firefly-db-backup
    namespace: finance
  register: firefly_db_job_status
  until: >
    firefly_db_job_status.resources | length > 0 and
    (firefly_db_job_status.resources[0].status.conditions | default([]) |
    selectattr('type', 'equalto', 'Complete') |
    selectattr('status', 'equalto', 'True') | list | length > 0)
  retries: 6
  delay: 5

- name: "Find DB dumps in PVC"
  become: true
  register: firefly_db_pvc_dumps
  ansible.builtin.find:
    paths: "{{ firefly_db_pvc_folder_search.files[0].path }}"
    file_type: "file"
    recurse: false

- name: "Find files in host backup directory"
  register: firefly_db_host_dumps
  ansible.builtin.find:
    paths: "{{ firefly_db_backup_directory }}"
    file_type: file
    recurse: false

- name: "Copy dumps from PVC to host"
  become: true
  loop: "{{ firefly_db_pvc_dumps.files }}"
  loop_control:
    label: "{{ item.path }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ firefly_db_backup_directory }}/{{ item.path | basename }}"
    remote_src: true
    mode: "0444"

- name: "Delete backup files in host not present in PVC"
  loop: "{{ firefly_db_host_dumps.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.path | basename not in firefly_db_pvc_dumps.files | map(attribute='path') | map('basename') | list
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent

- name: "Sync backups to Google Drive"
  changed_when: true
  ansible.builtin.script: "rclone.sh -source {{ firefly_db_backup_directory }} -destination {{ firefly_db_rclone_remote }}"
