- name: "Launch DB backup job"
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/db_backup_job.yaml"

- name: "Wait for DB backup job to complete"
  kubernetes.core.k8s_info:
    kind: Job
    name: firefly-firefly-db-backup
    namespace: finance
  register: job_status
  until: >
    job_status.resources | length > 0 and
    (job_status.resources[0].status.conditions | default([]) |
    selectattr('type', 'equalto', 'Complete') |
    selectattr('status', 'equalto', 'True') | list | length > 0)
  retries: 6
  delay: 5

- name: "Copy dump from PVC to host"
  when: pvc_folder_search.matched > 0
  block:

    - name: "Set variables"
      ansible.builtin.set_fact:
        firefly_backup_pvc_dump: "{{ pvc_folder_search.files[0].path }}/firefly.sql"
        firefly_backup_host_dump: "{{ firefly_db_backup_directory }}/firefly_{{ ansible_facts.date_time.iso8601_basic_short }}.sql.enc"

    - name: "Encrypt DB dump"
      # no_log: true
      become: true
      ansible.builtin.shell:
        cmd: >-
          openssl enc -aes-256-cbc -salt -pbkdf2
          -in {{ firefly_backup_pvc_dump }}
          -out {{ firefly_backup_host_dump }}
          -pass "pass:{{ firefly_db_dump_encrypt_password }}"

    - name: "Set permission for encrypted DB dump"
      become: true
      when: pvc_folder_search.matched > 0
      ansible.builtin.file:
        mode: "0644"
        owner: "{{ ansible_facts.user_id }}"
        path: "{{ firefly_backup_host_dump }}"

  always:
    - name: "Delete plain DB dump"
      become: true
      ansible.builtin.file:
        path: "{{ firefly_backup_pvc_dump }}"
        state: "absent"
        
