- name: "Launch DB backup job"
  ansible.builtin.shell:
    cmd: -|
      kubectl create job --from=cronjob/firefly-firefly-db-backup firefly-firefly-db-backup-job -n finance
      kubectl wait --for=condition=complete job firefly-firefly-db-backup-job --timeout=30s -n finance

- name: "Backup Firefly DB dump to host"
  become: true
  ansible.builtin.copy:
    dest: "{{ firefly_backup_directory }}/firefly_{{ ansible_date_time.iso8601_basic_short }}.sql"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    remote_src: true
    src: "{{ pvc_folder_search.files[0].path }}/firefly.sql"
