- name: "Create Firefly backup folder"
  ansible.builtin.file:
    path: "{{ firefly_db_backup_directory }}"
    state: "directory"
    mode: "0755"

- name: "Get Firefly backup PVC volume"
  kubernetes.core.k8s_info:
    kind: "PersistentVolumeClaim"
    name: "firefly-firefly-db-backup-storage-claim"
    namespace: "finance"
  register: "firefly_db_backup_pvc"

- name: "Find the host directory of the PVC"
  become: true
  register: firefly_db_pvc_folder_search
  ansible.builtin.find:
    file_type: "directory"
    paths: "{{ firefly_db_backup_k3s_pvc_directory }}"
    patterns: "{{ firefly_db_backup_pvc.resources[0].spec.volumeName }}*"
    recurse: false

- name: "Output host directory of PVC"
  ansible.builtin.debug:
    msg: "{{ firefly_db_pvc_folder_search.files | map(attribute='path') | list }}"
