- name: "Sync backups from Google Drive"
  changed_when: true
  ansible.builtin.script: "rclone.sh -source {{ firefly_db_rclone_remote }} -destination {{ firefly_db_backup_directory }}"

- name: "Copy dumps from host to PVC"
  become: true
  ansible.builtin.copy:
    src: "{{ firefly_db_backup_directory }}/{{ firefly_db_raw_dump }}"
    dest: "{{ firefly_db_pvc_folder_search.files[0].path }}/{{ firefly_db_raw_dump }}"
    remote_src: true
    mode: "0444"

- name: "Launch DB restore job"
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/db_restore_job.yaml"

- name: "Wait for DB restore job to complete"
  kubernetes.core.k8s_info:
    kind: Job
    name: firefly-firefly-db-restore
    namespace: finance
  register: firefly_db_job_status
  until: >
    firefly_db_job_status.resources | length > 0 and
    (firefly_db_job_status.resources[0].status.conditions | default([]) |
    selectattr('type', 'equalto', 'Complete') |
    selectattr('status', 'equalto', 'True') | list | length > 0)
  retries: 6
  delay: 5
