apiVersion: v2
name: argocd
version: 1.0.0
dependencies:
- name: argo-cd
  version: 5.32.1 # Newest version: 5.33.3
  repository: https://argoproj.github.io/argo-helm
- name: nginx-ingress
  version: 0.17.1
  repository: https://helm.nginx.com/stable
