resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi

pvc:
  accessMode: ReadWriteOnce
  size: 1Gi

serviceAccount:
  annotations: {}

rclone:
  config: AgDZKyYWmq3+YLTaom1ab5wye96rrSWt8BPzJrcDWSk9zq9bPdDR5C3Q30+7o/GnI0WLIzIFdR5j2tWUzB8bMu6Jh+6DBFCK3FK/wWEpA7BNz0MeZZ8kBMo3jRiW29mlSvUfaR81RyZOEWWra9tdmKSjAufWCzGWdainaCQE+Fb2ocEdR9wdoroWfcJjdzGzxRT8ozLmQBhedHr2+ffbMP91GLYp5Pda+Rt8+a0MV19C2+XmJWDjosz3kg7Wu4TOHOaFrTvDMdgtAhrM4tKuw3J+1ryqHEn+enteZd6rEM5am0ChECHJdNiLCpz8HRNFzAeQJc2i6EQ+OMtN44o6v5SK31yRRVqs0DQXyD5KOVtFdg+UNz8J9P2qgh8FnLrG4lq57Uyy8YApGa160P3Xi3ShqgnrlWDQx1LtqjMtZGc8/gqHaIklrOXSvnotA0dD8zrJPw3BA4+FPDS0sII1y0gpr4EEMVMB1v8SZG15aBGL5MBMMSpcFw5Pfwk290vMdRX1JWroHD9rKKiGcg26RMUKH/RL3u5QL7vbKyhRAp/7K+fhNl4NA35M0LUA2ZawLfJAUmos4S4Le+mWPwOsfprCBOrIa7wvretMUV8g76Q9tTZlu4picGRl+zwjvdxVzuOfvdibhb67r6THAoQ94qLDQlPWTIPcO5rpA+ERi5yi/Pnd5myj8GZUIJr6Fg2+tx96Bxfj4C+dCjwzn9mcONSSNdGg6bT+6LBMeq6/i9sxgOCEQaFjqh8M26L90nj4rMqHhmw30zE1JdUte97GH2oV5qDQ6I3fsUU1pC50yOUJkC/9RGeEer6+mPfZGQlgMmcnSrBnUiu+NHWlUpQ+9SRKoLOLjwAaMT7wD+3fd4DOORRavqJkUA1eKcbR9wA+AYqykAI1JqQzVUal5VR7W5mL7d9KaGsQ1H90n9kq7BTMHVCQuzoZ1bOnh6I7bIG3u5Dz2jXN2nJ69n2d9v4AeVUMa2x/U5Zoq5wFKMOqz49Bnv/3MHIcC+RXvPauRWUziMqgs6xdxbgKk2dCinsg0SEIWL7BPyF3JXMPT0Sr4hHKEDKqbDCo3zUyFv4lGyWtmGmepiVtThoTq4NUtUpXL2Qk6gR3ZclKHJrZGV1SaVP5BXoUQuWgu4d0F1TpfDiKPkz80gxinwNxEGIKZSOJhl/QoHtMgO+JeHpDp9+RC/97qobDPigYdA0KaqRaMWUq/hqtqD7tXVSIi9GagDvcjQyk5+UDu075e3KLsDC7G6mqIk6avZIzfOZL6HFwq3lPS2cV9vjBMbqr/bL1xt/AhnhuWRxH6WzRuBl+ann8aI1IU8NQOcS9DwAdp4j0GgU+7GyYkxn4egrGW/woZ9lzILDYVWgNFO3LUDhkZXDQLWsz0oz63ITw6MagkSbX1fTzhFGIPD01XLyCxYOpsUTfDXtzrffcymo4P4V1TYJ/tVZVDq3+h344yj+xj3lsY9Bj2quKimazhLoqo7+0hYGm5AnSR5kLF54D6kRvrDOfFVdDzZTXQRsBchCBBD5rXuKheGuu0+MZo9g0MpDfnRnBHiBbjiB/ovgxH1kAnTNjIH64aMnSIOTahvd0KbfQVpXJYuvl76q1Ov6AE6zb19/w3iqwFRVprzKLgaLVw92oSCQCpHJsrZ/dyQ4PJjkkGyPF+F37CgJr28HvBCKy5BgQmZ+msyst3AthP4ntfvqHTxzj5jkOBQZHGG9KnsoMIkzfwZa8J3u75WmZpGlVWV/oLJqreRLTwliVLvUaerfhJ0qcwIrDVVh3Z2IUlEJmPyTQUXy3MqdglKfsnw6oh+jkQiyBGZ6wxOSkqFg3NhjjY46doNrwsZ4exW6yV70=
  image:
    name: rclone/rclone
    tag: 1.74.2

firefly:
  db_config:
    DBHOST: firefly-firefly-db.finance
    DBNAME: firefly
    DBPORT: "5432"
    DBUSER: firefly
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: firefly

psqlClient:
  image: alpine/psql
  tag: 17.5

kubectlClient:
  image: alpine/kubectl
  tag: 1.36.1

busybox:
  image: busybox
  tag: 1.38.0
